In [3]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.5 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import tqdm
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from catboost import CatBoostClassifier

In [5]:
df=pd.read_csv("student_performance.csv")
df.head()

   student_id  weekly_self_study_hours  ...  total_score  grade
0           1                     18.5  ...         97.9      A
1           2                     14.0  ...         83.9      B
2           3                     19.5  ...        100.0      A
3           4                     25.7  ...        100.0      A
4           5                     13.4  ...         92.0      A

[5 rows x 6 columns]

In [6]:
df.describe()

           student_id  ...     total_score
count  1000000.000000  ...  1000000.000000
mean    500000.500000  ...       84.283845
std     288675.278933  ...       15.432969
min          1.000000  ...        9.400000
25%     250000.750000  ...       73.900000
50%     500000.500000  ...       87.500000
75%     750000.250000  ...      100.000000
max    1000000.000000  ...      100.000000

[8 rows x 5 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 6 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   student_id               1000000 non-null  int64
 1   weekly_self_study_hours  1000000 non-null  float64
 2   attendance_percentage    1000000 non-null  float64
 3   class_participation      1000000 non-null  float64
 4   total_score              1000000 non-null  float64
 5   grade                    1000000 non-null  object
dtypes: float64(4), int64(1), object(1)
memory usage: 45.8+ MB

In [8]:
df.shape

(1000000, 6)

In [9]:
df.isna().sum()

student_id                 0
weekly_self_study_hours    0
attendance_percentage      0
class_participation        0
total_score                0
grade                      0
dtype: int64

In [11]:
x=df.drop(["student_id","grade"],axis=1)

In [12]:
y=df["grade"]

In [14]:
x.head()

   weekly_self_study_hours  ...  total_score
0                     18.5  ...         97.9
1                     14.0  ...         83.9
2                     19.5  ...        100.0
3                     25.7  ...        100.0
4                     13.4  ...         92.0

[5 rows x 4 columns]

In [15]:
y.head()

0    A
1    B
2    A
3    A
4    A
Name: grade, dtype: object

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [25]:
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
preprocessor=ColumnTransformer(
    transformers=[
        ("scaler",StandardScaler(),x.columns)
    ]
)

In [26]:
from sklearn.model_selection import  train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [27]:
x_train

        weekly_self_study_hours  ...  total_score
566853                     23.0  ...        100.0
382311                     16.9  ...        100.0
241519                     10.8  ...         58.9
719220                     13.2  ...         93.2
905718                     14.0  ...         73.6
...                         ...  ...          ...
259178                      8.2  ...         83.1
365838                     10.5  ...         61.1
131932                     11.5  ...         92.3
671155                     12.9  ...         86.5
121958                      8.3  ...         65.3

[800000 rows x 4 columns]

In [28]:
x_test

        weekly_self_study_hours  ...  total_score
987231                      3.9  ...         53.9
79954                      17.1  ...         77.3
567130                      8.7  ...         75.0
500891                     15.0  ...         85.7
55399                       0.9  ...         30.8
...                         ...  ...          ...
90245                      17.7  ...        100.0
639296                     16.1  ...        100.0
311939                     24.6  ...        100.0
324459                      0.1  ...         34.6
390499                     14.3  ...         89.0

[200000 rows x 4 columns]

In [29]:
from sklearn.ensemble import RandomForestClassifier
rc=RandomForestClassifier(n_estimators=100)
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()
from xgboost import XGBClassifier
xgb=XGBClassifier()
cb=CatBoostClassifier()

In [48]:
from sklearn.pipeline import Pipeline
pip1=Pipeline(
    [
        ("preprocessing",preprocessor),
        ("model",rc)
    ]
)

In [44]:
pip1.fit(x_train,y_train)

Learning rate set to 0.111271
0:	learn: 1.1954437	total: 1.27s	remaining: 21m 14s
1:	learn: 0.9555209	total: 2s	remaining: 16m 35s
2:	learn: 0.7894930	total: 2.7s	remaining: 14m 58s
3:	learn: 0.6645454	total: 3.39s	remaining: 14m 5s
4:	learn: 0.5665719	total: 4.1s	remaining: 13m 35s
5:	learn: 0.4876100	total: 4.82s	remaining: 13m 17s
6:	learn: 0.4226728	total: 5.23s	remaining: 12m 22s
7:	learn: 0.3683608	total: 5.63s	remaining: 11m 38s
8:	learn: 0.3224741	total: 6.03s	remaining: 11m 3s
9:	learn: 0.2834357	total: 6.41s	remaining: 10m 34s
10:	learn: 0.2499349	total: 7.03s	remaining: 10m 31s
11:	learn: 0.2208498	total: 7.75s	remaining: 10m 37s
12:	learn: 0.1956860	total: 8.47s	remaining: 10m 43s
13:	learn: 0.1737942	total: 9.22s	remaining: 10m 49s
14:	learn: 0.1546883	total: 9.95s	remaining: 10m 53s
15:	learn: 0.1378496	total: 10.4s	remaining: 10m 39s
16:	learn: 0.1230514	total: 10.8s	remaining: 10m 23s
17:	learn: 0.1100265	total: 11.2s	remaining: 10m 10s
18:	learn: 0.0985533	total: 11.6s	remaining: 9m 58s
19:	learn: 0.0883832	total: 12s	remaining: 9m 46s
20:	learn: 0.0794151	total: 12.4s	remaining: 9m 36s
21:	learn: 0.0713376	total: 12.8s	remaining: 9m 27s
22:	learn: 0.0642329	total: 13.2s	remaining: 9m 18s
23:	learn: 0.0579465	total: 13.5s	remaining: 9m 10s
24:	learn: 0.0523756	total: 13.9s	remaining: 9m 3s
25:	learn: 0.0473448	total: 14.3s	remaining: 8m 56s
26:	learn: 0.0429165	total: 14.7s	remaining: 8m 50s
27:	learn: 0.0389848	total: 15.1s	remaining: 8m 44s
28:	learn: 0.0354312	total: 15.5s	remaining: 8m 38s
29:	learn: 0.0322274	total: 15.9s	remaining: 8m 33s
30:	learn: 0.0293951	total: 16.3s	remaining: 8m 29s
31:	learn: 0.0269235	total: 16.7s	remaining: 8m 24s
32:	learn: 0.0247051	total: 17.1s	remaining: 8m 20s
33:	learn: 0.0226626	total: 17.5s	remaining: 8m 16s
34:	learn: 0.0208730	total: 17.9s	remaining: 8m 12s
35:	learn: 0.0192905	total: 18.3s	remaining: 8m 8s
36:	learn: 0.0178104	total: 18.7s	remaining: 8m 5s
37:	learn: 0.0165623	total: 19.1s	remaining: 8m 2s
38:	learn: 0.0153965	total: 19.5s	remaining: 8m
39:	learn: 0.0143598	total: 19.9s	remaining: 7m 57s
40:	learn: 0.0134387	total: 20.4s	remaining: 7m 56s
41:	learn: 0.0126254	total: 21.1s	remaining: 8m
42:	learn: 0.0118870	total: 21.8s	remaining: 8m 5s
43:	learn: 0.0112271	total: 22.5s	remaining: 8m 9s
44:	learn: 0.0106316	total: 23.2s	remaining: 8m 12s
45:	learn: 0.0100718	total: 23.7s	remaining: 8m 11s
46:	learn: 0.0095955	total: 24.1s	remaining: 8m 9s
47:	learn: 0.0091522	total: 24.5s	remaining: 8m 6s
48:	learn: 0.0087541	total: 24.9s	remaining: 8m 4s
49:	learn: 0.0084050	total: 25.3s	remaining: 8m 1s
50:	learn: 0.0081036	total: 25.7s	remaining: 7m 58s
51:	learn: 0.0078087	total: 26.1s	remaining: 7m 56s
52:	learn: 0.0075554	total: 26.5s	remaining: 7m 53s
53:	learn: 0.0073195	total: 26.9s	remaining: 7m 51s
54:	learn: 0.0071171	total: 27.4s	remaining: 7m 50s
55:	learn: 0.0069368	total: 28.1s	remaining: 7m 53s
56:	learn: 0.0067691	total: 29s	remaining: 7m 59s
57:	learn: 0.0066177	total: 29.9s	remaining: 8m 5s
58:	learn: 0.0064832	total: 30.7s	remaining: 8m 9s
59:	learn: 0.0063796	total: 31.6s	remaining: 8m 14s
60:	learn: 0.0062641	total: 32.5s	remaining: 8m 20s
61:	learn: 0.0061703	total: 33.3s	remaining: 8m 23s
62:	learn: 0.0060804	total: 34.3s	remaining: 8m 30s
63:	learn: 0.0059857	total: 35.4s	remaining: 8m 37s
64:	learn: 0.0059458	total: 36.5s	remaining: 8m 44s
65:	learn: 0.0059141	total: 37.5s	remaining: 8m 50s
66:	learn: 0.0058517	total: 38.4s	remaining: 8m 55s
67:	learn: 0.0057988	total: 39.2s	remaining: 8m 56s
68:	learn: 0.0057511	total: 39.6s	remaining: 8m 54s
69:	learn: 0.0057282	total: 40.1s	remaining: 8m 52s
70:	learn: 0.0057073	total: 40.5s	remaining: 8m 49s
71:	learn: 0.0056788	total: 40.9s	remaining: 8m 46s
72:	learn: 0.0056517	total: 41.2s	remaining: 8m 43s
73:	learn: 0.0056382	total: 41.6s	remaining: 8m 40s
74:	learn: 0.0056257	total: 42s	remaining: 8m 37s
75:	learn: 0.0055781	total: 42.4s	remaining: 8m 35s
76:	learn: 0.0055676	total: 42.7s	remaining: 8m 32s
77:	learn: 0.0055270	total: 43.1s	remaining: 8m 29s
78:	learn: 0.0054936	total: 43.6s	remaining: 8m 27s
79:	learn: 0.0054725	total: 44s	remaining: 8m 25s
80:	learn: 0.0054650	total: 44.3s	remaining: 8m 23s
81:	learn: 0.0054330	total: 44.8s	remaining: 8m 21s
82:	learn: 0.0054247	total: 45.1s	remaining: 8m 18s
83:	learn: 0.0054090	total: 45.5s	remaining: 8m 16s
84:	learn: 0.0053944	total: 45.9s	remaining: 8m 14s
85:	learn: 0.0053891	total: 46.3s	remaining: 8m 12s
86:	learn: 0.0053746	total: 46.7s	remaining: 8m 10s
87:	learn: 0.0053461	total: 47.1s	remaining: 8m 8s
88:	learn: 0.0053258	total: 47.5s	remaining: 8m 6s
89:	learn: 0.0053206	total: 47.9s	remaining: 8m 4s
90:	learn: 0.0052989	total: 48.3s	remaining: 8m 2s
91:	learn: 0.0052736	total: 49s	remaining: 8m 3s
92:	learn: 0.0052549	total: 49.7s	remaining: 8m 5s
93:	learn: 0.0052354	total: 50.5s	remaining: 8m 6s
94:	learn: 0.0052300	total: 51.1s	remaining: 8m 6s
95:	learn: 0.0052217	total: 51.7s	remaining: 8m 7s
96:	learn: 0.0052167	total: 52.1s	remaining: 8m 5s
97:	learn: 0.0052026	total: 52.5s	remaining: 8m 3s
98:	learn: 0.0051990	total: 52.9s	remaining: 8m 1s
99:	learn: 0.0051845	total: 53.3s	remaining: 8m
100:	learn: 0.0051771	total: 53.7s	remaining: 7m 58s
101:	learn: 0.0051681	total: 54.1s	remaining: 7m 56s
102:	learn: 0.0051540	total: 54.5s	remaining: 7m 54s
103:	learn: 0.0051504	total: 55s	remaining: 7m 53s
104:	learn: 0.0051474	total: 55.3s	remaining: 7m 51s
105:	learn: 0.0051417	total: 55.7s	remaining: 7m 49s
106:	learn: 0.0051338	total: 56.1s	remaining: 7m 47s
107:	learn: 0.0051199	total: 56.5s	remaining: 7m 46s
108:	learn: 0.0051154	total: 56.9s	remaining: 7m 44s
109:	learn: 0.0051096	total: 57.3s	remaining: 7m 43s
110:	learn: 0.0051066	total: 57.7s	remaining: 7m 41s
111:	learn: 0.0051034	total: 58s	remaining: 7m 39s
112:	learn: 0.0050941	total: 58.4s	remaining: 7m 38s
113:	learn: 0.0050910	total: 58.8s	remaining: 7m 37s
114:	learn: 0.0050881	total: 59.2s	remaining: 7m 35s
115:	learn: 0.0050796	total: 59.6s	remaining: 7m 33s
116:	learn: 0.0050773	total: 59.9s	remaining: 7m 32s
117:	learn: 0.0050744	total: 1m	remaining: 7m 30s
118:	learn: 0.0050694	total: 1m	remaining: 7m 29s
119:	learn: 0.0050670	total: 1m 1s	remaining: 7m 27s
120:	learn: 0.0050642	total: 1m 1s	remaining: 7m 26s
121:	learn: 0.0050624	total: 1m 1s	remaining: 7m 25s
122:	learn: 0.0050598	total: 1m 2s	remaining: 7m 26s
123:	learn: 0.0050562	total: 1m 3s	remaining: 7m 27s
124:	learn: 0.0050518	total: 1m 3s	remaining: 7m 27s
125:	learn: 0.0050500	total: 1m 4s	remaining: 7m 28s
126:	learn: 0.0050412	total: 1m 5s	remaining: 7m 27s
127:	learn: 0.0050390	total: 1m 5s	remaining: 7m 26s
128:	learn: 0.0050375	total: 1m 5s	remaining: 7m 24s
129:	learn: 0.0050355	total: 1m 6s	remaining: 7m 23s
130:	learn: 0.0050325	total: 1m 6s	remaining: 7m 22s
131:	learn: 0.0050299	total: 1m 7s	remaining: 7m 20s
132:	learn: 0.0050210	total: 1m 7s	remaining: 7m 19s
133:	learn: 0.0050189	total: 1m 7s	remaining: 7m 18s
134:	learn: 0.0050148	total: 1m 8s	remaining: 7m 17s
135:	learn: 0.0050055	total: 1m 8s	remaining: 7m 16s
136:	learn: 0.0049966	total: 1m 9s	remaining: 7m 15s
137:	learn: 0.0049942	total: 1m 9s	remaining: 7m 13s
138:	learn: 0.0049909	total: 1m 9s	remaining: 7m 12s
139:	learn: 0.0049886	total: 1m 10s	remaining: 7m 11s
140:	learn: 0.0049840	total: 1m 10s	remaining: 7m 10s
141:	learn: 0.0049821	total: 1m 11s	remaining: 7m 9s
142:	learn: 0.0049799	total: 1m 11s	remaining: 7m 7s
143:	learn: 0.0049773	total: 1m 11s	remaining: 7m 6s
144:	learn: 0.0049698	total: 1m 12s	remaining: 7m 5s
145:	learn: 0.0049688	total: 1m 12s	remaining: 7m 4s
146:	learn: 0.0049607	total: 1m 12s	remaining: 7m 3s
147:	learn: 0.0049599	total: 1m 13s	remaining: 7m 2s
148:	learn: 0.0049585	total: 1m 13s	remaining: 7m 1s
149:	learn: 0.0049567	total: 1m 14s	remaining: 6m 59s
150:	learn: 0.0049537	total: 1m 14s	remaining: 6m 58s
151:	learn: 0.0049523	total: 1m 14s	remaining: 6m 57s
152:	learn: 0.0049498	total: 1m 15s	remaining: 6m 57s
153:	learn: 0.0049471	total: 1m 16s	remaining: 6m 58s
154:	learn: 0.0049453	total: 1m 16s	remaining: 6m 58s
155:	learn: 0.0049440	total: 1m 17s	remaining: 6m 58s
156:	learn: 0.0049411	total: 1m 18s	remaining: 6m 59s
157:	learn: 0.0049391	total: 1m 18s	remaining: 6m 58s
158:	learn: 0.0049320	total: 1m 18s	remaining: 6m 57s
159:	learn: 0.0049279	total: 1m 19s	remaining: 6m 56s
160:	learn: 0.0049261	total: 1m 19s	remaining: 6m 55s
161:	learn: 0.0049194	total: 1m 20s	remaining: 6m 54s
162:	learn: 0.0049129	total: 1m 20s	remaining: 6m 53s
163:	learn: 0.0049109	total: 1m 20s	remaining: 6m 52s
164:	learn: 0.0049091	total: 1m 21s	remaining: 6m 51s
165:	learn: 0.0049062	total: 1m 21s	remaining: 6m 50s
166:	learn: 0.0049040	total: 1m 22s	remaining: 6m 49s
167:	learn: 0.0048978	total: 1m 22s	remaining: 6m 48s
168:	learn: 0.0048918	total: 1m 22s	remaining: 6m 47s
169:	learn: 0.0048910	total: 1m 23s	remaining: 6m 46s
170:	learn: 0.0048854	total: 1m 23s	remaining: 6m 45s
171:	learn: 0.0048774	total: 1m 24s	remaining: 6m 44s
172:	learn: 0.0048713	total: 1m 24s	remaining: 6m 43s
173:	learn: 0.0048693	total: 1m 24s	remaining: 6m 42s
174:	learn: 0.0048682	total: 1m 25s	remaining: 6m 41s
175:	learn: 0.0048665	total: 1m 25s	remaining: 6m 40s
176:	learn: 0.0048637	total: 1m 25s	remaining: 6m 39s
177:	learn: 0.0048593	total: 1m 26s	remaining: 6m 38s
178:	learn: 0.0048542	total: 1m 26s	remaining: 6m 38s
179:	learn: 0.0048523	total: 1m 27s	remaining: 6m 36s
180:	learn: 0.0048504	total: 1m 27s	remaining: 6m 36s
181:	learn: 0.0048454	total: 1m 27s	remaining: 6m 35s
182:	learn: 0.0048431	total: 1m 28s	remaining: 6m 34s
183:	learn: 0.0048420	total: 1m 28s	remaining: 6m 34s
184:	learn: 0.0048394	total: 1m 29s	remaining: 6m 35s
185:	learn: 0.0048357	total: 1m 30s	remaining: 6m 35s
186:	learn: 0.0048340	total: 1m 31s	remaining: 6m 35s
187:	learn: 0.0048323	total: 1m 31s	remaining: 6m 35s
188:	learn: 0.0048304	total: 1m 32s	remaining: 6m 34s
189:	learn: 0.0048269	total: 1m 32s	remaining: 6m 34s
190:	learn: 0.0048258	total: 1m 32s	remaining: 6m 33s
191:	learn: 0.0048240	total: 1m 33s	remaining: 6m 32s
192:	learn: 0.0048225	total: 1m 33s	remaining: 6m 31s
193:	learn: 0.0048218	total: 1m 33s	remaining: 6m 30s
194:	learn: 0.0048200	total: 1m 34s	remaining: 6m 29s
195:	learn: 0.0048186	total: 1m 34s	remaining: 6m 28s
196:	learn: 0.0048180	total: 1m 35s	remaining: 6m 27s
197:	learn: 0.0048128	total: 1m 35s	remaining: 6m 26s
198:	learn: 0.0048114	total: 1m 35s	remaining: 6m 25s
199:	learn: 0.0048101	total: 1m 36s	remaining: 6m 24s
200:	learn: 0.0048086	total: 1m 36s	remaining: 6m 23s
201:	learn: 0.0048070	total: 1m 36s	remaining: 6m 23s
202:	learn: 0.0048062	total: 1m 37s	remaining: 6m 22s
203:	learn: 0.0048041	total: 1m 37s	remaining: 6m 21s
204:	learn: 0.0048021	total: 1m 38s	remaining: 6m 20s
205:	learn: 0.0047997	total: 1m 38s	remaining: 6m 19s
206:	learn: 0.0047986	total: 1m 38s	remaining: 6m 18s
207:	learn: 0.0047966	total: 1m 39s	remaining: 6m 18s
208:	learn: 0.0047946	total: 1m 39s	remaining: 6m 17s
209:	learn: 0.0047931	total: 1m 40s	remaining: 6m 16s
210:	learn: 0.0047896	total: 1m 40s	remaining: 6m 15s
211:	learn: 0.0047885	total: 1m 40s	remaining: 6m 14s
212:	learn: 0.0047870	total: 1m 41s	remaining: 6m 13s
213:	learn: 0.0047855	total: 1m 41s	remaining: 6m 13s
214:	learn: 0.0047842	total: 1m 42s	remaining: 6m 13s
215:	learn: 0.0047833	total: 1m 42s	remaining: 6m 13s
216:	learn: 0.0047816	total: 1m 43s	remaining: 6m 14s
217:	learn: 0.0047805	total: 1m 44s	remaining: 6m 14s
218:	learn: 0.0047799	total: 1m 44s	remaining: 6m 14s
219:	learn: 0.0047782	total: 1m 45s	remaining: 6m 13s
220:	learn: 0.0047767	total: 1m 45s	remaining: 6m 12s
221:	learn: 0.0047755	total: 1m 46s	remaining: 6m 11s
222:	learn: 0.0047731	total: 1m 46s	remaining: 6m 10s
223:	learn: 0.0047719	total: 1m 46s	remaining: 6m 9s
224:	learn: 0.0047712	total: 1m 47s	remaining: 6m 9s
225:	learn: 0.0047696	total: 1m 47s	remaining: 6m 8s
226:	learn: 0.0047679	total: 1m 47s	remaining: 6m 7s
227:	learn: 0.0047667	total: 1m 48s	remaining: 6m 6s
228:	learn: 0.0047648	total: 1m 48s	remaining: 6m 5s
229:	learn: 0.0047635	total: 1m 49s	remaining: 6m 5s
230:	learn: 0.0047622	total: 1m 49s	remaining: 6m 4s
231:	learn: 0.0047613	total: 1m 49s	remaining: 6m 3s
232:	learn: 0.0047596	total: 1m 50s	remaining: 6m 2s
233:	learn: 0.0047577	total: 1m 50s	remaining: 6m 2s
234:	learn: 0.0047566	total: 1m 51s	remaining: 6m 1s
235:	learn: 0.0047559	total: 1m 51s	remaining: 6m
236:	learn: 0.0047546	total: 1m 51s	remaining: 5m 59s
237:	learn: 0.0047522	total: 1m 52s	remaining: 5m 59s
238:	learn: 0.0047502	total: 1m 52s	remaining: 5m 58s
239:	learn: 0.0047488	total: 1m 52s	remaining: 5m 57s
240:	learn: 0.0047482	total: 1m 53s	remaining: 5m 56s
241:	learn: 0.0047438	total: 1m 53s	remaining: 5m 56s
242:	learn: 0.0047426	total: 1m 54s	remaining: 5m 55s
243:	learn: 0.0047398	total: 1m 54s	remaining: 5m 54s
244:	learn: 0.0047380	total: 1m 55s	remaining: 5m 54s
245:	learn: 0.0047372	total: 1m 55s	remaining: 5m 54s
246:	learn: 0.0047361	total: 1m 56s	remaining: 5m 54s
247:	learn: 0.0047343	total: 1m 57s	remaining: 5m 54s
248:	learn: 0.0047329	total: 1m 57s	remaining: 5m 55s
249:	learn: 0.0047319	total: 1m 58s	remaining: 5m 55s
250:	learn: 0.0047313	total: 1m 58s	remaining: 5m 54s
251:	learn: 0.0047302	total: 1m 59s	remaining: 5m 53s
252:	learn: 0.0047294	total: 1m 59s	remaining: 5m 52s
253:	learn: 0.0047285	total: 1m 59s	remaining: 5m 52s
254:	learn: 0.0047270	total: 2m	remaining: 5m 51s
255:	learn: 0.0047261	total: 2m	remaining: 5m 50s
256:	learn: 0.0047252	total: 2m 1s	remaining: 5m 49s
257:	learn: 0.0047245	total: 2m 1s	remaining: 5m 49s
258:	learn: 0.0047234	total: 2m 1s	remaining: 5m 48s
259:	learn: 0.0047225	total: 2m 2s	remaining: 5m 47s
260:	learn: 0.0047216	total: 2m 2s	remaining: 5m 47s
261:	learn: 0.0047212	total: 2m 3s	remaining: 5m 46s
262:	learn: 0.0047183	total: 2m 3s	remaining: 5m 45s
263:	learn: 0.0047171	total: 2m 3s	remaining: 5m 45s
264:	learn: 0.0047161	total: 2m 4s	remaining: 5m 44s
265:	learn: 0.0047137	total: 2m 4s	remaining: 5m 43s
266:	learn: 0.0047132	total: 2m 4s	remaining: 5m 43s
267:	learn: 0.0047124	total: 2m 5s	remaining: 5m 42s
268:	learn: 0.0047108	total: 2m 5s	remaining: 5m 41s
269:	learn: 0.0047079	total: 2m 6s	remaining: 5m 41s
270:	learn: 0.0047061	total: 2m 6s	remaining: 5m 40s
271:	learn: 0.0047056	total: 2m 7s	remaining: 5m 39s
272:	learn: 0.0047043	total: 2m 7s	remaining: 5m 39s
273:	learn: 0.0047022	total: 2m 7s	remaining: 5m 38s
274:	learn: 0.0047008	total: 2m 8s	remaining: 5m 38s
275:	learn: 0.0047004	total: 2m 8s	remaining: 5m 37s
276:	learn: 0.0046985	total: 2m 9s	remaining: 5m 38s
277:	learn: 0.0046963	total: 2m 10s	remaining: 5m 38s
278:	learn: 0.0046950	total: 2m 10s	remaining: 5m 38s
279:	learn: 0.0046937	total: 2m 11s	remaining: 5m 38s
280:	learn: 0.0046929	total: 2m 12s	remaining: 5m 37s
281:	learn: 0.0046920	total: 2m 12s	remaining: 5m 37s
282:	learn: 0.0046909	total: 2m 12s	remaining: 5m 36s
283:	learn: 0.0046895	total: 2m 13s	remaining: 5m 35s
284:	learn: 0.0046866	total: 2m 13s	remaining: 5m 35s
285:	learn: 0.0046853	total: 2m 13s	remaining: 5m 34s
286:	learn: 0.0046830	total: 2m 14s	remaining: 5m 34s
287:	learn: 0.0046799	total: 2m 14s	remaining: 5m 33s
288:	learn: 0.0046786	total: 2m 15s	remaining: 5m 32s
289:	learn: 0.0046779	total: 2m 15s	remaining: 5m 32s
290:	learn: 0.0046770	total: 2m 16s	remaining: 5m 31s
291:	learn: 0.0046749	total: 2m 16s	remaining: 5m 31s
292:	learn: 0.0046730	total: 2m 16s	remaining: 5m 30s
293:	learn: 0.0046719	total: 2m 17s	remaining: 5m 29s
294:	learn: 0.0046708	total: 2m 17s	remaining: 5m 29s
295:	learn: 0.0046692	total: 2m 18s	remaining: 5m 28s
296:	learn: 0.0046672	total: 2m 18s	remaining: 5m 27s
297:	learn: 0.0046661	total: 2m 18s	remaining: 5m 27s
298:	learn: 0.0046648	total: 2m 19s	remaining: 5m 26s
299:	learn: 0.0046641	total: 2m 19s	remaining: 5m 25s
300:	learn: 0.0046625	total: 2m 20s	remaining: 5m 25s
301:	learn: 0.0046606	total: 2m 20s	remaining: 5m 24s
302:	learn: 0.0046600	total: 2m 20s	remaining: 5m 23s
303:	learn: 0.0046589	total: 2m 21s	remaining: 5m 23s
304:	learn: 0.0046580	total: 2m 21s	remaining: 5m 22s
305:	learn: 0.0046566	total: 2m 22s	remaining: 5m 22s
306:	learn: 0.0046564	total: 2m 22s	remaining: 5m 22s
307:	learn: 0.0046549	total: 2m 23s	remaining: 5m 22s
308:	learn: 0.0046544	total: 2m 24s	remaining: 5m 22s
309:	learn: 0.0046539	total: 2m 24s	remaining: 5m 22s
310:	learn: 0.0046530	total: 2m 25s	remaining: 5m 21s
311:	learn: 0.0046526	total: 2m 25s	remaining: 5m 21s
312:	learn: 0.0046512	total: 2m 25s	remaining: 5m 20s
313:	learn: 0.0046503	total: 2m 26s	remaining: 5m 19s
314:	learn: 0.0046491	total: 2m 26s	remaining: 5m 19s
315:	learn: 0.0046483	total: 2m 27s	remaining: 5m 18s
316:	learn: 0.0046467	total: 2m 27s	remaining: 5m 17s
317:	learn: 0.0046454	total: 2m 27s	remaining: 5m 17s
318:	learn: 0.0046435	total: 2m 28s	remaining: 5m 16s
319:	learn: 0.0046425	total: 2m 28s	remaining: 5m 15s
320:	learn: 0.0046409	total: 2m 29s	remaining: 5m 15s
321:	learn: 0.0046399	total: 2m 29s	remaining: 5m 14s
322:	learn: 0.0046385	total: 2m 29s	remaining: 5m 14s
323:	learn: 0.0046374	total: 2m 30s	remaining: 5m 13s
324:	learn: 0.0046354	total: 2m 30s	remaining: 5m 12s
325:	learn: 0.0046345	total: 2m 31s	remaining: 5m 12s
326:	learn: 0.0046323	total: 2m 31s	remaining: 5m 11s
327:	learn: 0.0046307	total: 2m 31s	remaining: 5m 11s
328:	learn: 0.0046296	total: 2m 32s	remaining: 5m 10s
329:	learn: 0.0046276	total: 2m 32s	remaining: 5m 9s
330:	learn: 0.0046257	total: 2m 32s	remaining: 5m 9s
331:	learn: 0.0046247	total: 2m 33s	remaining: 5m 8s
332:	learn: 0.0046234	total: 2m 33s	remaining: 5m 7s
333:	learn: 0.0046227	total: 2m 34s	remaining: 5m 7s
334:	learn: 0.0046218	total: 2m 34s	remaining: 5m 6s
335:	learn: 0.0046203	total: 2m 34s	remaining: 5m 6s
336:	learn: 0.0046190	total: 2m 35s	remaining: 5m 5s
337:	learn: 0.0046172	total: 2m 36s	remaining: 5m 5s
338:	learn: 0.0046166	total: 2m 36s	remaining: 5m 5s
339:	learn: 0.0046156	total: 2m 37s	remaining: 5m 5s
340:	learn: 0.0046137	total: 2m 38s	remaining: 5m 5s
341:	learn: 0.0046123	total: 2m 38s	remaining: 5m 5s
342:	learn: 0.0046109	total: 2m 39s	remaining: 5m 4s
343:	learn: 0.0046100	total: 2m 39s	remaining: 5m 3s
344:	learn: 0.0046093	total: 2m 39s	remaining: 5m 3s
345:	learn: 0.0046067	total: 2m 40s	remaining: 5m 2s
346:	learn: 0.0046058	total: 2m 40s	remaining: 5m 2s
347:	learn: 0.0046049	total: 2m 40s	remaining: 5m 1s
348:	learn: 0.0046030	total: 2m 41s	remaining: 5m
349:	learn: 0.0045988	total: 2m 41s	remaining: 5m
350:	learn: 0.0045973	total: 2m 42s	remaining: 4m 59s
351:	learn: 0.0045958	total: 2m 42s	remaining: 4m 59s
352:	learn: 0.0045931	total: 2m 42s	remaining: 4m 58s
353:	learn: 0.0045917	total: 2m 43s	remaining: 4m 58s
354:	learn: 0.0045904	total: 2m 43s	remaining: 4m 57s
355:	learn: 0.0045895	total: 2m 44s	remaining: 4m 56s
356:	learn: 0.0045871	total: 2m 44s	remaining: 4m 56s
357:	learn: 0.0045864	total: 2m 44s	remaining: 4m 55s
358:	learn: 0.0045850	total: 2m 45s	remaining: 4m 55s
359:	learn: 0.0045839	total: 2m 45s	remaining: 4m 54s
360:	learn: 0.0045822	total: 2m 46s	remaining: 4m 54s
361:	learn: 0.0045809	total: 2m 46s	remaining: 4m 53s
362:	learn: 0.0045796	total: 2m 46s	remaining: 4m 52s
363:	learn: 0.0045792	total: 2m 47s	remaining: 4m 52s
364:	learn: 0.0045781	total: 2m 47s	remaining: 4m 51s
365:	learn: 0.0045771	total: 2m 48s	remaining: 4m 51s
366:	learn: 0.0045761	total: 2m 48s	remaining: 4m 50s
367:	learn: 0.0045756	total: 2m 49s	remaining: 4m 50s
368:	learn: 0.0045744	total: 2m 49s	remaining: 4m 50s
369:	learn: 0.0045735	total: 2m 50s	remaining: 4m 50s
370:	learn: 0.0045720	total: 2m 51s	remaining: 4m 50s
371:	learn: 0.0045710	total: 2m 51s	remaining: 4m 50s
372:	learn: 0.0045703	total: 2m 52s	remaining: 4m 49s
373:	learn: 0.0045694	total: 2m 52s	remaining: 4m 48s
374:	learn: 0.0045687	total: 2m 52s	remaining: 4m 48s
375:	learn: 0.0045677	total: 2m 53s	remaining: 4m 47s

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('scaler', StandardScaler(),
                                                  Index(['weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score'],
      dtype='object'))])),
                ('model', CatBoostClassifier())])

In [45]:
y_pred=pip1.predict(x_test)
y2=pip1.predict(x_train)

In [46]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.99783

In [47]:
print(accuracy_score(y_train,y2))

0.99823